---
# Influxdb create user

- name: Create user
  uri:
    url: http://{{ ansible_fqdn }}:8086/query?u={{ influxdb_admin_user }}&p={{ influxdb_admin_password }}
    method: POST
    body: "q=CREATE USER {{ influxdb_user_name }} WITH PASSWORD '{{ influxdb_password_user }}'"
  when: influxdb_create_user

- include: influxdb_privilege.yml
