---
# Influxdb configuration

- name: Set net.core.rmem_max & net.core.rmem_default
  sysctl:
    name: "{{ item }}"
    value: 26214400
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.core.rmem_max
    - net.core.rmem_default

- name: Create admin user
  uri:
    url: http://{{ ansible_fqdn }}:8086/query?u={{ influxdb_admin_user }}&p={{ influxdb_admin_password }}
    method: POST
    body: "q=CREATE USER {{ influxdb_admin_user }} WITH PASSWORD '{{ influxdb_admin_password }}' WITH ALL PRIVILEGES"

- name: Upload InfluxDB configuration file
  template: src=influxdb.conf.j2 dest={{ influxdb_conf_path }}influxdb.conf owner=root group=root mode=0644
  register: upload_change

- name: restart influxdb
  service: name={{ influxdb_service_name }} state=restarted
  when: upload_change|changed

- name: wait for influxdb
  wait_for: port={{ influxdb_meta_port }} delay=10

- include: influxdb_bdd.yml
  when: influxdb_create_database

- include: influxdb_user.yml
  when: influxdb_create_user
